#!/usr/bin/env node
// -*-Javascript-*-

/* eslint-disable no-process-exit */
/* eslint-disable global-require */

'use strict';

// core modules
const http = require('http');
const https = require('https');
const url = require('url');
const path = require('path');

// local modules
const nad = require('nad');
const settings = require(path.join(nad.lib_dir, 'settings'));
const Plugins = require(path.join(nad.lib_dir, 'plugins'));

const log = settings.logger.child({ module: 'main' });

let plugins = null;         // plugin manager
let push_receiver = null;   // listener, metrics can be 'pushed' to nad
let circwmi = null;         // dynamically load, if platform is windows
let statsd = null;          // dynamically load in finish_bootstrap, if enabled
let reverse = null;         // dynamically load in finish_bootstrap, if enabled

log.info('initializing');

if (settings.is_windows) {
    try {
        log.info('loading WMI module for Windows platform');
        circwmi = require('circwmi');
    } catch (err) {
        const msg = 'unable to load circwmi module';

        log.fatal({ err }, msg);
        console.error(settings.pfx_error, msg, err);
        process.exit(1);
    }
}

// handler processes web requests
function handler(req, res) {
    const bodyChunks = [];

    req.addListener('data', (chunk) => {
        bodyChunks.push(chunk);
    });

    req.addListener('end', () => {
        let matches = null;
        const url_parts = url.parse(req.url);
        const url_path = url_parts.pathname;
        const body = Buffer.concat(bodyChunks).toString();

        log.debug({ method: req.method, path: url_path, base: req.url }, 'request');
        if (req.method === 'GET') {
            // request for meta-info about the loaded plugins
            if (/^\/inventory$/.test(url_path)) {
                const full = (/\?full/).test(url_parts.search);

                log.debug('inventory request');
                res.writeHead(200, { 'Content-Type': 'application/json' });
                res.write(plugins.inventory(full));
                res.end();
                return;
            }

            // request to run all plugins and return results
            if (/^\/(?:run)?$/.test(url_path)) {
                log.debug('running all scripts');
                plugins.run(req, res, null);
                return;
            }

            // request to run just one plugin and return results
            matches = (/^\/run\/(.+)$/).exec(url_path);
            if (matches) {
                log.debug({ script: matches[1] }, 'running plugin');
                plugins.run(req, res, matches[1]);
                return;
            }

            // wmi-specific
            if (settings.is_windows) {
                if ((/^\/wmi\/get-categories$/).test(url_path)) {
                    log.debug('wmi categories request');
                    circwmi.get_categories(res);
                    return;
                }
                matches = (/^\/wmi\/(.+)$/).exec(url_path);
                if (matches) {
                    log.debug({ category: matches[1] }, 'wmi counters request');
                    circwmi.get_counters_for_category(res, matches[1], settings.debug_dir, settings.wipe_debug_dir);
                    return;
                }
            }
        }

        // push plugin
        if (push_receiver !== null) {
            matches = (/^\/write\/(.+)$/).exec(url_path);
            if (matches) {
                if (req.method !== 'PUT' && req.method !== 'POST') {
                    res.writeHead(405, 'Method Not Allowed', { Allow : 'PUT, POST' });
                    res.end();
                    return;
                }
                push_receiver.native_obj.store_incoming_data(matches[1], body);
                res.writeHead(200, 'OK', { 'Content-Type': 'text/plan' });
                res.end();
                return;
            }
        }

        // otherwise... consider it an invalid request

        log.debug({ method: req.method, path: url_path }, 'invalid request');
        res.writeHead(404, 'invalid request');
        res.end();
    });

    // if we don't have a data listener the stream starts paused in node 10+
    req.addListener('data', () => {});
}

// finish_bootstrap completes the loading process after plugins have been scanned
function finish_bootstrap() {

    function start_statsd() {
        if (!settings.statsd.enabled) {
            log.debug('statsd not enabled, skipping');
            return;
        }

        log.info('initializing statsd listener');
        try {
            statsd = require(path.join(nad.lib_dir, 'statsd'));
            statsd.start();
        } catch (err) {
            const errMsg = `unable to start statsd listener`;

            log.fatal({ err: err.message }, errMsg);
            console.error(settings.pfx_error, errMsg, err);
            process.exit(1);
        }
    }

    function start_reverse() {
        if (!settings.reverse.enabled) {
            log.debug('reverse not enabled, skipping');
            start_statsd();
            return;
        }

        // NOTE: if reverse is enabled, have it call start_statsd
        //       after it finishes initializing ensure that the
        //       statsd module has a host_check_id. reverse will
        //       update settings if it has to 'search' for
        //       a check and one is found.

        log.info('setting up reverse connection');
        try {
            reverse = require(path.join(nad.lib_dir, 'reverse'));
        } catch (err) {
            const errMsg = `unable to load reverse connection module`;

            log.fatal({ err: err.message }, errMsg);
            console.error(settings.pfx_error, errMsg, err);
            process.exit(1);
        }

        reverse().
            then(() => {
                start_statsd();
            }).
            catch((err) => {
                const errMsg = `unable to set up reverse connection`;

                log.fatal({ err: err.message }, errMsg);
                console.error(settings.pfx_error, errMsg, err);
                process.exit(1);

            });
    }

    for (const server of settings.listen) {
        log.debug({ server }, 'starting server');

        try {
            http.createServer(handler).listen(server.port, server.address);
            log.info({ server }, 'started');
        } catch (err) {
            const msg = 'failed to start server';

            log.fatal({ server, err }, msg);
            console.error(settings.pfx_error, msg, server, err);
            process.exit(-1);
        }
    }

    for (const server of settings.ssl.listen) {
        log.debug({ server }, 'starting SSL server');

        try {
            https.createServer(settings.ssl.creds, handler).listen(server.port, server.address);
            log.info({ server }, 'started (SSL)');
        } catch (err) {
            const msg = 'failed to start SSL server';

            log.fatal({ server, err }, msg);
            console.error(settings.pfx_error, msg, server, err);
            process.exit(-1);
        }
    }

    log.debug('installing SIGHUP handler to trigger plugin rescan');
    process.on('SIGHUP', () => {
        log.info('SIGHUP received, re-scanning plugins');
        plugins.scan();
    });

    if (settings.drop_uid > 0 && process.setuid) {
        log.info({ uid: settings.drop_uid }, 'dropping privileges');
        process.setuid(settings.drop_uid);
    }

    if (global.gc) {
        setInterval(() => {
            log.info('running gc');
            global.gc();
        }, 300 * 1000);
    }

    start_reverse();
}

log.debug('loading push receiver handler');
try {
    let PushReceiver = null;

    try {
        PushReceiver = require(path.join(nad.lib_dir, 'push_receiver'));
    } catch (err) {
        const msg = 'failed to load push_recever module';

        log.fatal({ err }, msg);
        console.error(settings.pfx_error, msg, err);
        process.exit(1);
    }

    // NOTE: this *simulates* a regular plugin
    push_receiver = Plugins.new_plugin('push_receiver');
    push_receiver.is_native = true;
    push_receiver.native_obj = new PushReceiver({ log });
} catch (err) {
    const msg = 'unable to initialize push receiver';

    log.fatal({ err }, msg);
    console.log(settings.pfx_error, msg, err);
    process.exit(1);
}
log.info('push receiver handler loaded');

// initialize plugin manager
plugins = new Plugins.Manager(push_receiver);

// initial scan for plugins, then finish bootstrapping NAD
plugins.scan(finish_bootstrap);

// END
